### ISSUE TITLE
Traitors are able to see Doppels if a role has been copied

### ISSUE THREAD

**Issue by The1337Gh0st** [ZacharyHinds/ttt2-role-dop#10]
If a Doppel copies the role of another player, the Traitors are able to see the copied role of the Doppel. This can be a dead giveaway for Traitors if they can see someone with a role they normally aren't supposed to see (e.g. an Innocent Doppel).

**Comment by ZacharyHinds** [comment]
Fixed with the most recent [commit](https://github.com/ZacharyHinds/ttt2-role-dop/commit/4ac979f4cbe1d45b346b69b4490d4d72c12fc0d3)
