### ISSUE TITLE
Bug Report: Infected spawned by a Doppelganger aren't on the Doppelganger's team

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-dop#3]
**Description:**
When the Doppelganger steals the Infected Role, any Infected they spawn from killing players are placed on the original Infected's Team, instead of the Doppelganger's team.

**Notes:**

- The doppelganger infected is still treated as the infected host, and all infected spawned by them will perish once they dies, despite not being on the same team.
- Since the Infected zombies aren't on the same team as the Infected Doppelganger, the infected Doppelganger is forced to kill all of his spawned Infected if they wish to win.  

**Expected Result:** Infected spawned by a Doppelganger Infected are on the Doppelganger's team.

**Actual Result:** Infected spawned by the Doppelganger Infected are on the original Infected's team.

**Comment by ZacharyHinds** [comment]
Added Special Handling for Doppelganger role-stealing Infected, they will now become Unknown (or Innocent if Unknown is not installed).

Can be disabled with "ttt2_dop_infected"
