### ISSUE TITLE
Bug Report: Doppleganger Mesmerist using the Defib revives the Thrall on the Traitor team

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-dop#4]
**Description:**
When the Doppelganger steals the Mesmerist Role and revives a dead player as a Thrall using the Defib, they are on the Traitor team instead of the Doppelganger team.

**Notes:**

- This behavior is inconsistent with the behavior of the Jackal Role. When the Doppelganger steals the Jackal role, anyone they convert into a Sidekick using the Sidekick Deagle are placed on the Doppelganger's team instead of the Jackal team.

**Expected Result:** Reviving a dead player as a Doppelganger Mesmerist revives the Thrall on the Doppelganger team.

**Actual Result:** Reviving a dead player as a Doppelganger Mesmerist revives the Thrall on the Traitor team.

**Comment by ZacharyHinds** [comment]
Not added to this role, but I have fixed this by adding a new option to the Mesmerist/Thrall:

"ttt2_thr_inherit_team 1" forces the Thrall to inherit the Mesmerist's team, regardless of whether or not that is the Traitors or Doppelgangers (or Lovers if you use the Cupid role).
