### ISSUE TITLE
Bug Report: Doppelganger/Mimic does not gain the Jester's win condition when stealing the role

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-dop#5]
**Description:**
When the Doppelganger/Mimic steals the Jester Role, they do not gain any of the Jester win conditions.

**Notes:**

- This results in the Doppelganger/Mimic being unable to win, as they can no longer deal damage to players, and killing the Doppelganger/Mimic results in nothing happening.
- The interaction should likely be handled similar to the special case Marker interaction, where the Doppelganger/Mimic transform into the Amnesiac role instead of the Jester. This would prevent it from being an overpowered interaction, and saves the headache of ensuring all of the Jester win conditions work as intended.

**Expected Result:** Stealing the Jester's role allows the Doppelganger/Mimic to gain their win condition.

**Actual Result:** Stealing the Jester's Role as Doppelganger/Mimic does not grant the win condition, rendering it impossible to win the round.

**Comment by ZacharyHinds** [comment]
Added Special Handling for Doppelganger stealing Jester, they will now become Amnesiac (OR Unkown if Amnesiac not installed OR Innocent if neither Unkown/Amnesiac installed).

Mimic role-stealing Jester works fine, so this is specific to Doppelganger.

Can be disabled with "ttt2_dop_jester 0"
