### ISSUE TITLE
Bug Report/Quality of Life: Doppelganger stealing the Beacon role is converted to the Innocent team after killing an Innocent

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-dop#6]
**Description:**
If the Doppelganger steals the Beacon's role and then kills a member of the innocent team, they are converted to the Innocent team.

**Notes:**

- Normally, the Beacon killing an innocent player swaps the Beacon's role back to the default Innocent, as a punishment, and this interaction is not technically a bug. However, this is an incredibly feel bad moment for the Doppelganger, as they're not only converted into a normal Innocent, but also have their team swapped to the Innocent team as well. Ideally, the Doppelganger would remain on his own team after being transformed into a normal Innocent.

**Expected Result:** Killing an innocent as a Doppelganger Beacon turns the Doppelganger into an innocent but stays on the Doppelganger team.

**Actual Result:** Killing an Innocent as a Doppelganger Beacon turns the Doppelganger into an innocent and swaps them to the Innocent team.

**Comment by ZacharyHinds** [comment]
Added Special Handling for Beacon, Doppelganger will now become regular Innocent when role-stealing Beacon

Can be disabled with "ttt2_dop_beacon 0"
