### ISSUE TITLE
Mesmerist + Doppelganger: All Thralls are now Doppleganger team sided regardless of who revived

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-dop#7]
Description:
Since a recent update, whenever a Mesermist attempts to revive a dead player as a thrall, the Thrall will always be on the Doppleganger team even if the Mesermist was a T and there was no Dopplegangers in the round originally.

Notes:

- Sadly don't have a recording, and idk if its related to specific convars, but i've seen enough people complain about it that im 100% certain it is happening.

**Comment by ZacharyHinds** [comment]
Ah my bad, I was aware of this issue. Should be fixed on steam, forgot to push the commit here to fix
